variables:
  REGION: asia-southeast1
  IMAGE_NAME: vb-listen-smc-job
  APP_NAME_SUPPLY: vb-listen-smc-supply
  APP_NAME_BORROW: vb-listen-smc-borrow
  APP_NAME_REPAY: vb-listen-smc-repay
  APP_NAME_JOB_LENDING: vb-listen-smc-job-lending
  APP_NAME_WITHDRAW: vb-listen-smc-withdraw
  APP_NAME_RSV_UDT: vb-listen-smc-rsv-udt
  # APP_NAME_PAIR_CRT: vb-listen-smc-pair-crt
 # APP_NAME_JOB_POOL: vb-listen-smc-job-pool
  CONTAINER_REPO_ASIA_STAG: 968557029040.dkr.ecr.ap-southeast-1.amazonaws.com/vb-staging-ecr/listen-smc-job
  CONTAINER_REPO_ASIA_PROD: 968557029040.dkr.ecr.ap-southeast-1.amazonaws.com/vb-production-ecr/listen-smc-job
  NAMESPACE_STAG: vb-jobs-stag
  NAMESPACE_PROD: vb-jobs
  FULLREPO_ASIA_STAG: $CONTAINER_REPO_ASIA_STAG:$CI_COMMIT_SHA
  FULLREPO_ASIA_PROD: $CONTAINER_REPO_ASIA_PROD:$CI_COMMIT_SHA
  HELM_VALUE: ${CI_COMMIT_REF_NAME}
  HELM_VERSION: 3.0.0
  KUBECTL_VERSION: v1.22.0
  SKAFFOLD_VERSION: v1.38.0
  HELM_CRONJOB_VERSION: 0.1.9
  AWS_REGION: ap-southeast-1
  GITLAB_TOKEN: $GITLAB_RUNNER_TOKEN
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

.kubectl_config: &kubectl_config
  - |
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        aws eks --region $AWS_REGION update-kubeconfig --name esol-production-cluster
      fi
  - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        aws eks --region $AWS_REGION update-kubeconfig --name esol-staging-cluster
      fi
.predeploy: &predeploy |
  apk add --no-cache  bash git  python3 py3-pip curl
  pip3 install --upgrade pip 
  pip3 install --no-cache-dir awscli
  helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.12.0
  helm repo add helm-template s3://esol-helm-template
  helm repo add helm-template-cronjob s3://esol-helm-template/cronjob
  helm pull s3://esol-helm-template/helm-template-$HELM_VERSION.tgz --untar=true
  helm pull s3://esol-helm-template/cronjob/helm-template-cronjob-$HELM_CRONJOB_VERSION.tgz --untar=true

build_stag:
  image: docker:19.03.1
  tags:
  - esol-stag
  stage: build
  services:
  - docker:19.03.1-dind
  before_script:
    - apk add --no-cache curl jq python py-pip wget git bash
    - pip install awscli 
 #   - git submodule add --branch stag https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/rinz-io/rinz-lib.git lib
    - export VERIFY_CHECKSUM=false && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod +x ./get_helm.sh && ./get_helm.sh
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/$SKAFFOLD_VERSION/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
  #  - git submodule sync --recursive
  #  - git submodule update --init --remote --recursive
  script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $CONTAINER_REPO_ASIA_STAG
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$IMAGE_NAME#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
        cat skaffold.yaml
      fi
    - /usr/local/bin/skaffold build -p profile-stag --file-output=build_sync.json
  only:
    refs:
      - stag
   
  artifacts:
    paths:
    - build_sync.json

deploy_borrow_stag:
  stage: deploy
  image:  alpine/helm:3.2.1
  tags:
  - esol-stag
  script:
    - *predeploy
    - *kubectl_config
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_BORROW#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/rinz-io-devops/helm-value/$IMAGE_NAME.git
    - mv $IMAGE_NAME/${APP_NAME_BORROW}-stag.yaml .
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/$SKAFFOLD_VERSION/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_BORROW}-stag   -a build_sync.json

  only:
    refs:
      - stag
 
deploy_repay_stag:
  stage: deploy
  image:  alpine/helm:3.2.1
  tags:
  - esol-stag
  script:
    - *predeploy
    - *kubectl_config
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_REPAY#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/rinz-io-devops/helm-value/$IMAGE_NAME.git
    - mv $IMAGE_NAME/${APP_NAME_REPAY}-stag.yaml .
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/$SKAFFOLD_VERSION/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_REPAY}-stag   -a build_sync.json

  only:
    refs:
      - stag
   
deploy_withdraw_stag:
  stage: deploy
  image:  alpine/helm:3.2.1
  tags:
  - esol-stag
  script:
    - *predeploy
    - *kubectl_config
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_WITHDRAW#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/rinz-io-devops/helm-value/$IMAGE_NAME.git
    - mv $IMAGE_NAME/${APP_NAME_WITHDRAW}-stag.yaml .
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/$SKAFFOLD_VERSION/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_WITHDRAW}-stag   -a build_sync.json

  only:
    refs:
      - stag
  

deploy_supply_stag:
  stage: deploy
  image:  alpine/helm:3.2.1
  tags:
  - esol-stag
  script:
    - *predeploy
    - *kubectl_config
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_SUPPLY#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/rinz-io-devops/helm-value/$IMAGE_NAME.git
    - mv $IMAGE_NAME/${APP_NAME_SUPPLY}-stag.yaml .
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/$SKAFFOLD_VERSION/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_SUPPLY}-stag   -a build_sync.json

  only:
    refs:
      - stag

deploy_rsv_udt_stag:
  stage: deploy
  image:  alpine/helm:3.2.1
  tags:
  - esol-stag
  script:
    - *predeploy
    - *kubectl_config
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_RSV_UDT#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/rinz-io-devops/helm-value/$IMAGE_NAME.git
    - mv $IMAGE_NAME/${APP_NAME_RSV_UDT}-stag.yaml .
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/$SKAFFOLD_VERSION/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_RSV_UDT}-stag   -a build_sync.json

  only:
    refs:
      - stag
      
deploy_job_lending_stag:
  stage: deploy
  image:  alpine/helm:3.2.1
  tags:
  - esol-stag
  script:
    - *predeploy
    - *kubectl_config
    - |
      if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
        sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
        sed -i -e "s#\[APP_NAME\]#$APP_NAME_JOB_LENDING#g" skaffold.yaml
        sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
        sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
      fi
    - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/rinz-io-devops/helm-value/$IMAGE_NAME.git
    - mv $IMAGE_NAME/${APP_NAME_JOB_LENDING}-stag.yaml .
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/$SKAFFOLD_VERSION/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
    - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_JOB_LENDING}-cronjob-stag   -a build_sync.json
    - kubectl set image cronjob/$APP_NAME_JOB_LENDING-stag $APP_NAME_JOB_LENDING-stag=$FULLREPO_ASIA_STAG -n $NAMESPACE_STAG

  only:
    refs:
      - stag
  

# deploy_pair_created_stag:
#   stage: deploy
#   image:  alpine/helm:3.2.1
#   tags:
#   - esol-stag
#   script:
#     - *predeploy
#     - *kubectl_config
#     - |
#       if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
#         sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
#         sed -i -e "s#\[APP_NAME\]#$APP_NAME_PAIR_CRT#g" skaffold.yaml
#         sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
#         sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
#       fi
#     - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/rinz-io-devops/helm-value/$IMAGE_NAME.git
#     - mv $IMAGE_NAME/${APP_NAME_PAIR_CRT}-stag.yaml .
#     - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
#     - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/$SKAFFOLD_VERSION/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
#     - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_PAIR_CRT}-cronjob-stag   -a build_sync.json

#   only:
#     refs:
#       - stag


# deploy_job_pool_stag:
#   stage: deploy
#   image:  alpine/helm:3.2.1
#   tags:
#   - esol-stag
#   script:
#     - *predeploy
#     - *kubectl_config
#     - |
#       if [ "$CI_COMMIT_REF_NAME" == "stag" ]; then
#         sed -i -e "s#\[NAMESPACE\]#$NAMESPACE_STAG#g" skaffold.yaml
#         sed -i -e "s#\[APP_NAME\]#$APP_NAME_JOB_POOL#g" skaffold.yaml
#         sed -i -e "s#\[CONTAINER_REPO\]#$CONTAINER_REPO_ASIA_STAG#g" skaffold.yaml
#         sed -i -e "s#\[CI_COMMIT_REF_NAME\]#$CI_COMMIT_REF_NAME#g" skaffold.yaml
#       fi
#     - git clone https://read-token:$GITLAB_TOKEN@gitlab.rinznetwork.com/rinz-io-devops/helm-value/$IMAGE_NAME.git
#     - mv $IMAGE_NAME/${APP_NAME_JOB_POOL}-stag.yaml .
#     - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
#     - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/$SKAFFOLD_VERSION/skaffold-linux-amd64 && chmod +x skaffold &&  mv skaffold /usr/local/bin
#     - /usr/local/bin/skaffold deploy -p profile-${APP_NAME_JOB_POOL}-cronjob-stag   -a build_sync.json

#   only:
#     refs:
#       - stag