version: "3.2"

services:
  node:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    env_file:
      - .env
    ports:
      - 3005:3000
    networks:
      - vebank-jobs

networks:
  vebank-jobs: